### ISSUE TITLE
tieredImagenet model？

### ISSUE THREAD

**Issue by ning-ac** [ShuoYang-1998/ICLR2021-Oral_Distribution_Calibration#1]
Hi, thank you for your nice work！
I notice that there are only CUB and miniImagenet models in the Drive, how about the tieredImagenet mode and corresponding files? Thank you very much.

**Comment by ShuoYang-1998** [comment]
Hi, thanks for your comment! Since the tieredImagenet experiment was included during the rebuttal period, the related code and model have not been merged into this original codebase yet. You can refer to [https://github.com/nupurkmr9/S2M2_fewshot](url) for details about training the tiered dataset. Thanks.

**Comment by ning-ac** [comment]
Ok, thank you for your reply. However, I still hope you can add the tieredImagent files in the future.
Thank you for your work again!
